ch12n – specfun
ch12n Subroutine
45 statements
Source File
public subroutine ch12n(n, z, Nm, Chf1, Chd1, Chf2, Chd2)
Compute Hankel functions of the first and second kinds and their derivatives for a complex argument
Arguments
Type Intent Optional Attributes Name
integer :: n
complex(kind=wp) :: z
integer :: Nm
complex(kind=wp), dimension(0:n) :: Chf1
complex(kind=wp), dimension(0:n) :: Chd1
complex(kind=wp), dimension(0:n) :: Chf2
complex(kind=wp), dimension(0:n) :: Chd2
Calls
Call graph
ch12n calls ciknb, cjynb
ciknb calls msta1, msta2
cjynb calls msta1, msta2
msta1 calls envj
msta2 calls envj