chgu – specfun
chgu Subroutine
55 statements
Source File
public subroutine chgu(a, b, x, Hu, Md, Isfer)
Compute the confluent hypergeometric function U(a,b,x)
Arguments
Type Intent Optional Attributes Name
real(kind=wp) :: a
real(kind=wp) :: b
real(kind=wp) :: x
real(kind=wp) :: Hu
integer :: Md
integer :: Isfer
Calls
Contents
None
Call graph
chgu calls chgus, chguit, chgubi, chgul
chgus calls gamma2
chguit calls gamma2
chgubi calls gamma2, psi_spec