ciknb – specfun
ciknb Subroutine
91 statements
Source File
public subroutine ciknb(n, z, Nm, Cbi, Cdi, Cbk, Cdk)
Compute modified Bessel functions In(z) and Kn(z), and their derivatives for a complex argument
Arguments
Type Intent Optional Attributes Name
integer :: n
complex(kind=wp) :: z
integer :: Nm
complex(kind=wp), dimension(0:n) :: Cbi
complex(kind=wp), dimension(0:n) :: Cdi
complex(kind=wp), dimension(0:n) :: Cbk
complex(kind=wp), dimension(0:n) :: Cdk
Calls
Called by
Call graph
ciknb calls msta1, msta2
msta1 calls envj
msta2 calls envj
ch12n calls ciknb