cikvb – specfun
cikvb Subroutine
141 statements
Source File
public subroutine cikvb(v, z, Vm, Cbi, Cdi, Cbk, Cdk)
Compute the modified Bessel functions Iv(z), Kv(z) and their derivatives for an arbitrary order and complex argument
Arguments
Type Intent Optional Attributes Name
real(kind=wp) :: v
complex(kind=wp) :: z
real(kind=wp) :: Vm
complex(kind=wp) :: Cbi
complex(kind=wp) :: Cdi
complex(kind=wp) :: Cbk
complex(kind=wp) :: Cdk
Calls
Contents
None
Call graph
cikvb calls gamma2, msta2, msta1
msta2 calls envj
msta1 calls envj