cjyvb – specfun
cjyvb Subroutine
145 statements
Source File
public subroutine cjyvb(v, z, Vm, Cbj, Cdj, Cby, Cdy)
Compute Bessel functions Jv(z), Yv(z) and their derivatives for a complex argument
Arguments
Type Intent Optional Attributes Name
real(kind=wp) :: v
complex(kind=wp) :: z
real(kind=wp) :: Vm
complex(kind=wp), dimension(0:*) :: Cbj
complex(kind=wp), dimension(0:*) :: Cdj
complex(kind=wp), dimension(0:*) :: Cby
complex(kind=wp), dimension(0:*) :: Cdy
Calls
Call graph
cjyvb calls gamma2, msta1, msta2
msta1 calls envj
msta2 calls envj