cvf – specfun
cvf Subroutine
36 statements
Source File
public subroutine cvf(Kd, m, q, a, Mj, f)
Compute the value of F for characteristic equation of Mathieu functions
Arguments
Type Intent Optional Attributes Name
integer :: Kd
integer :: m
real(kind=wp) :: q
real(kind=wp) :: a
integer :: Mj
real(kind=wp) :: f
Called by
Call graph
refine calls cvf
cva2 calls refine
mtu0 calls cva2
mtu12 calls cva2