cvqm – specfun
cvqm Subroutine
10 statements
Source File
public subroutine cvqm(m, q, a0)
Compute the characteristic value of Mathieu functions for q ≤ m*m
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: m
Order of Mathieu functions
real(kind=wp), intent(in) :: q
Parameter of Mathieu functions
real(kind=wp), intent(out) :: a0
Initial characteristic value
Called by
Source Code
   subroutine cvqm(m,q,a0)
      integer,intent(in) :: m !! Order of Mathieu functions
      real(wp),intent(in) :: q !! Parameter of Mathieu functions
      real(wp),intent(out) :: a0 !! Initial characteristic value
      real(wp) :: hm1 , hm3 , hm5
      hm1 = 0.5_wp*q/(m*m-1.0_wp)
      hm3 = 0.25_wp*hm1**3/(m*m-4.0_wp)
      hm5 = hm1*hm3*q/((m*m-1.0_wp)*(m*m-9.0_wp))
      a0 = m*m + q*(hm1+(5.0_wp*m*m+7.0_wp)*hm3+(9.0_wp*m**4+58.0_wp*m*m+29.0_wp)*hm5)
   end subroutine cvqm
Call graph
cv0 calls cvqm
cva2 calls cvqm, cv0
mtu0 calls cva2
mtu12 calls cva2