dnan – specfun
dnan Function
4 statements
Source File
public function dnan()
Arguments
None
Return Value real(kind=wp)
Called by
Contents
Source Code
dnan
Source Code
      real(wp) function dnan()
      dnan = 0.0_wp
      dnan = 0.0_wp/dnan
      end function dnan
Call graph
mtu0 calls dnan, fcoef
fcoef calls dnan
lpmv calls dnan
mtu12 calls dnan, fcoef