dvla – specfun
dvla Subroutine
21 statements
Source File
public subroutine dvla(Va, x, Pd)
Compute parabolic cylinder functions Dv(x) for large argument
Arguments
Type Intent Optional Attributes Name
real(kind=wp) :: Va
real(kind=wp) :: x
real(kind=wp) :: Pd
Calls
Called by
Call graph
dvla calls gamma2, vvla
vvla calls dvla, gamma2
pbdv calls dvla
pbvv calls vvla