envj – specfun
envj Function
5 statements
Source File
public function envj(n, x)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
real(kind=wp), intent(in) :: x
Return Value real(kind=wp)
Called by
Source Code
   real(wp) function envj(n,x)
      integer,intent(in) :: n
      real(wp),intent(in) :: x
      envj = 0.5_wp*log10(6.28_wp*n) - n*log10(1.36_wp*x/n)
   end function envj
Call graph
msta1 calls envj
msta2 calls envj
cikna calls msta1, msta2
ciknb calls msta1, msta2
cikva calls msta1, msta2
cikvb calls msta1, msta2
cjynb calls msta1, msta2
cjyva calls msta1, msta2
cjyvb calls msta1, msta2
ikna calls msta1, msta2
iknb calls msta1, msta2
ikv calls msta1, msta2
jyna calls msta1, msta2
jynbh calls msta1, msta2
jyv calls msta1, msta2
lamn calls msta1, msta2
lamv calls msta1, msta2
rctj calls msta1, msta2
sphi calls msta1, msta2
sphj calls msta1, msta2
ch12n calls ciknb, cjynb
jynb calls jynbh
jyndd calls jynbh
rmn1 calls sphj
jyzo calls jyndd
mtu12 calls jynb
rmn2so calls rmn1
rswfo calls rmn1, rmn2so
rswfp calls rmn1