fcoef – specfun
fcoef Subroutine
211 statements
Source File
public subroutine fcoef(Kd, m, q, a, Fc)
Compute expansion coefficients for Mathieu functions and modified Mathieu functions
Arguments
Type Intent Optional Attributes Name
integer :: Kd
integer :: m
real(kind=wp) :: q
real(kind=wp) :: a
real(kind=wp), dimension(251) :: Fc
Calls
Called by
Call graph
fcoef calls dnan
mtu0 calls fcoef
mtu12 calls fcoef