gamma2 – specfun
gamma2 Subroutine
36 statements
Source File
public subroutine gamma2(x, Ga)
Compute gamma function Г(x)
Arguments
Type Intent Optional Attributes Name
real(kind=wp) :: x
real(kind=wp) :: Ga
Called by
Contents
None
Call graph
chguit calls gamma2
cjyva calls gamma2
cjyvb calls gamma2
dvsa calls gamma2
vvla calls gamma2, dvla
chgubi calls gamma2
hygfx calls gamma2
hygfz calls gamma2
ikv calls gamma2
cikva calls gamma2
vvsa calls gamma2
dvla calls gamma2, vvla
incog calls gamma2
jyv calls gamma2
chgus calls gamma2
beta calls gamma2
lpmv calls gamma2
cikvb calls gamma2
chgu calls chguit, chgubi, chgus
pbdv calls dvsa, dvla
pbvv calls vvla, vvsa
incob calls beta