jynb – specfun
jynb Subroutine
22 statements
Source File
public subroutine jynb(n, x, Nm, Bj, Dj, By, Dy)
Compute Bessel functions Jn(x), Yn(x) and their derivatives
Arguments
Type Intent Optional Attributes Name
integer :: n
real(kind=wp) :: x
integer :: Nm
real(kind=wp), dimension(0:n) :: Bj
real(kind=wp), dimension(0:n) :: Dj
real(kind=wp), dimension(0:n) :: By
real(kind=wp), dimension(0:n) :: Dy
Calls
Called by
Call graph
jynb calls jynbh
jynbh calls msta1, msta2
msta1 calls envj
msta2 calls envj
mtu12 calls jynb