jynbh – specfun
jynbh Subroutine
96 statements
Source File
public subroutine jynbh(n, Nmin, x, Nm, Bj, By)
Compute Bessel functions Jn(x), Yn(x)
Arguments
Type Intent Optional Attributes Name
integer :: n
integer :: Nmin
real(kind=wp) :: x
integer :: Nm
real(kind=wp), dimension(0:n-nmin) :: Bj
real(kind=wp), dimension(0:n-nmin) :: By
Calls
Called by
Call graph
jynbh calls msta1, msta2
msta1 calls envj
msta2 calls envj
jynb calls jynbh
jyndd calls jynbh
jyzo calls jyndd
mtu12 calls jynb