jyzo – specfun
jyzo Subroutine
100 statements
Source File
public subroutine jyzo(n, Nt, Rj0, Rj1, Ry0, Ry1)
Compute the zeros of Bessel functions Jn(x), Yn(x), and their derivatives
Arguments
Type Intent Optional Attributes Name
integer :: n
integer :: Nt
real(kind=wp), dimension(nt) :: Rj0
real(kind=wp), dimension(nt) :: Rj1
real(kind=wp), dimension(nt) :: Ry0
real(kind=wp), dimension(nt) :: Ry1
Calls
Call graph
jyzo calls jyndd
jyndd calls jynbh
jynbh calls msta1, msta2
msta1 calls envj
msta2 calls envj