mtu0 – specfun
mtu0 Subroutine
52 statements
Source File
public subroutine mtu0(Kf, m, q, x, Csf, Csd)
Compute Mathieu functions cem(x,q) and sem(x,q) and their derivatives (q ≥ 0)
Arguments
Type Intent Optional Attributes Name
integer :: Kf
integer :: m
real(kind=wp) :: q
real(kind=wp) :: x
real(kind=wp) :: Csf
real(kind=wp) :: Csd
Calls
Contents
None
Call graph
mtu0 calls cva2, fcoef, dnan
cva2 calls cv0, cvql, refine, cvqm
fcoef calls dnan
cv0 calls cvql, cvqm
refine calls cvf