mtu12 – specfun
mtu12 Subroutine
91 statements
Source File
public subroutine mtu12(Kf, Kc, m, q, x, F1r, D1r, F2r, D2r)
Compute modified Mathieu functions of the first and second kinds, Mcm(1)(2)(x,q) and Msm(1)(2)(x,q), and their derivatives
Arguments
Type Intent Optional Attributes Name
integer :: Kf
integer :: Kc
integer :: m
real(kind=wp) :: q
real(kind=wp) :: x
real(kind=wp) :: F1r
real(kind=wp) :: D1r
real(kind=wp) :: F2r
real(kind=wp) :: D2r
Calls
Call graph
mtu12 calls cva2, dnan, fcoef, jynb
cva2 calls cv0, cvql, cvqm, refine
fcoef calls dnan
jynb calls jynbh
cv0 calls cvql, cvqm
jynbh calls msta1, msta2
refine calls cvf
msta1 calls envj
msta2 calls envj