pbdv – specfun
pbdv Subroutine
97 statements
Source File
public subroutine pbdv(v, x, Dv, Dp, Pdf, Pdd)
Compute parabolic cylinder functions Dv(x) and their derivatives
Arguments
Type Intent Optional Attributes Name
real(kind=wp) :: v
real(kind=wp) :: x
real(kind=wp), dimension(0:*) :: Dv
real(kind=wp), dimension(0:*) :: Dp
real(kind=wp) :: Pdf
real(kind=wp) :: Pdd
Calls
Call graph
pbdv calls dvla, dvsa
dvla calls gamma2, vvla
dvsa calls gamma2
vvla calls dvla, gamma2