pbvv – specfun
pbvv Subroutine
104 statements
Source File
public subroutine pbvv(v, x, Vv, Vp, Pvf, Pvd)
Compute parabolic cylinder functions Vv(x) and their derivatives
Arguments
Type Intent Optional Attributes Name
real(kind=wp) :: v
real(kind=wp) :: x
real(kind=wp), dimension(0:*) :: Vv
real(kind=wp), dimension(0:*) :: Vp
real(kind=wp) :: Pvf
real(kind=wp) :: Pvd
Calls
Call graph
pbvv calls vvla, vvsa
vvla calls dvla, gamma2
vvsa calls gamma2
dvla calls vvla, gamma2