psi_spec – specfun
psi_spec Subroutine
44 statements
Source File
public subroutine psi_spec(x, Ps)
Compute Psi function
Arguments
Type Intent Optional Attributes Name
real(kind=wp) :: x
real(kind=wp) :: Ps
Called by
Contents
None
Call graph
chgubi calls psi_spec
hygfx calls psi_spec
hygfz calls psi_spec
lpmv0 calls psi_spec
chgu calls chgubi
lpmv calls lpmv0