rmn2so – specfun
rmn2so Subroutine
44 statements
Source File
public subroutine rmn2so(m, n, c, x, Cv, Df, Kd, R2f, R2d)
Compute oblate radial functions of the second kind with a small argument, Rmn(-ic,ix) & Rmn'(-ic,ix)
Arguments
Type Intent Optional Attributes Name
integer :: m
integer :: n
real(kind=wp) :: c
real(kind=wp) :: x
real(kind=wp) :: Cv
real(kind=wp), dimension(200) :: Df
integer :: Kd
real(kind=wp) :: R2f
real(kind=wp) :: R2d
Calls
Called by
Call graph
rmn2so calls cbk, gmn, kmn, qstar, rmn1, sckb
rmn1 calls sckb, sphj
sphj calls msta1, msta2
msta1 calls envj
msta2 calls envj
rswfo calls rmn2so