rswfo – specfun
rswfo Subroutine
13 statements
Source File
public subroutine rswfo(m, n, c, x, Cv, Kf, R1f, R1d, R2f, R2d)
Compute oblate radial functions of the first and second kinds, and their derivatives
Arguments
Type Intent Optional Attributes Name
integer :: m
integer :: n
real(kind=wp) :: c
real(kind=wp) :: x
real(kind=wp) :: Cv
integer :: Kf
real(kind=wp) :: R1f
real(kind=wp) :: R1d
real(kind=wp) :: R2f
real(kind=wp) :: R2d
Calls
Contents
None
Call graph
rswfo calls sdmn, rmn2so, rmn1, rmn2l
rmn2so calls rmn1, sckb, cbk, qstar, kmn, gmn
rmn1 calls sckb, sphj
rmn2l calls sphy
sphj calls msta1, msta2
msta1 calls envj
msta2 calls envj