rswfp – specfun
rswfp Subroutine
21 statements
Source File
public subroutine rswfp(m, n, c, x, cv, Kf, R1f, R1d, R2f, R2d)
Compute prolate spheriodal radial functions of the first and second kinds, and their derivatives
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: m
Mode parameter, m = 0,1,2,...
integer, intent(in) :: n
Mode parameter, n = m,m+1,m+2,...
real(kind=wp), intent(in) :: c
Spheroidal parameter
real(kind=wp), intent(in) :: x
Argument of radial function (x > 1.0)
real(kind=wp), intent(in) :: cv
Characteristic value
integer, intent(in) :: Kf
Function code: * KF=1 for the first kind * KF=2 for the second kind * KF=3 for both the first and second kinds
real(kind=wp), intent(out) :: R1f
Radial function of the first kind
real(kind=wp), intent(out) :: R1d
Derivative of the radial function of the first kind
real(kind=wp), intent(out) :: R2f
Radial function of the second kind
real(kind=wp), intent(out) :: R2d
Derivative of the radial function of the second kind
Calls
Source Code
   subroutine rswfp(m,n,c,x,Cv,Kf,R1f,R1d,R2f,R2d)
      integer,intent(in) :: m  !! Mode parameter, `m = 0,1,2,...`
      integer,intent(in) :: n  !! Mode parameter, `n = m,m+1,m+2,...`
      real(wp),intent(in) :: c  !! Spheroidal parameter
      real(wp),intent(in) :: x  !! Argument of radial function ( `x > 1.0` )
      real(wp),intent(in) :: cv !! Characteristic value
      integer,intent(in) :: Kf !! Function code:
                               !!  * `KF=1` for the first kind
                               !!  * `KF=2` for the second kind
                               !!  * `KF=3` for both the first and second kinds
      real(wp),intent(out) :: R1f !! Radial function of the first kind
      real(wp),intent(out) :: R1d !! Derivative of the radial function of
                                  !! the first kind
      real(wp),intent(out) :: R2f !! Radial function of the second kind
      real(wp),intent(out) :: R2d !! Derivative of the radial function of
                                  !! the second kind
      real(wp) :: df(200)
      integer :: id , kd
      kd = 1
      call sdmn(m,n,c,Cv,kd,df)
      if ( Kf/=2 ) call rmn1(m,n,c,x,df,kd,R1f,R1d)
      if ( Kf>1 ) then
         call rmn2l(m,n,c,x,df,kd,R2f,R2d,id)
         if ( id>-8 ) call rmn2sp(m,n,c,x,Cv,df,kd,R2f,R2d)
      endif
   end subroutine rswfp
Call graph
rswfp calls rmn1, rmn2l, rmn2sp, sdmn
rmn1 calls sckb, sphj
rmn2l calls sphy
rmn2sp calls kmn, lpmns, lqmns
sphj calls msta1, msta2
msta1 calls envj
msta2 calls envj