sckb – specfun
sckb Subroutine
41 statements
Source File
public subroutine sckb(m, n, c, Df, Ck)
Arguments
Type Intent Optional Attributes Name
integer :: m
integer :: n
real(kind=wp) :: c
real(kind=wp) :: Df
real(kind=wp) :: Ck
Called by
Contents
None
Call graph
rmn1 calls sckb
aswfa calls sckb
rmn2so calls sckb, rmn1
rswfp calls rmn1
rswfo calls rmn1, rmn2so