sdmn – specfun
sdmn Subroutine
112 statements
Source File
public subroutine sdmn(m, n, c, Cv, Kd, Df)
Compute the expansion coefficients of the prolate and oblate spheroidal functions, dk
Arguments
Type Intent Optional Attributes Name
integer :: m
integer :: n
real(kind=wp) :: c
real(kind=wp) :: Cv
integer :: Kd
real(kind=wp), dimension(200) :: Df
Called by
Call graph
aswfa calls sdmn
aswfb calls sdmn
rswfo calls sdmn
rswfp calls sdmn