sphj – specfun
sphj Subroutine
47 statements
Source File
public subroutine sphj(n, x, Nm, Sj, Dj)
Compute spherical Bessel functions jn(x) and their derivatives
Arguments
Type Intent Optional Attributes Name
integer :: n
real(kind=wp) :: x
integer :: Nm
real(kind=wp), dimension(0:n) :: Sj
real(kind=wp), dimension(0:n) :: Dj
Calls
Called by
Call graph
sphj calls msta1, msta2
msta1 calls envj
msta2 calls envj
rmn1 calls sphj
rmn2so calls rmn1
rswfo calls rmn1, rmn2so
rswfp calls rmn1